### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by Quarterblad** [BinaryHackerLab/CadenceLicensePatcher#3]
Some text are missing, probably lack of fonts. 
![image](https://user-images.githubusercontent.com/26858463/232489334-45d4acbc-36f0-4ac6-8443-db257ded48a1.png)

**Comment by TerraWilly** [comment]
Hello bro,

I update it, please use new version

**Comment by Quarterblad** [comment]
> Hello bro,
> 
> I update it, please use new version

Yep, it works, tnx bro
