### ISSUE TITLE
patch sigrity 2023.1 problem

### ISSUE THREAD

**Issue by TwoBrushes** [BinaryHackerLab/CadenceLicensePatcher#5]
when use cadencelicensepatcher v2.0.0 to patch sigrity 2023.1, cadencelicensepatcher Crashed！

**Comment by TerraWilly** [comment]
Hello,

You need close XcitePI process. I will fix it in next version.

Thanks.

**Comment by TwoBrushes** [comment]
when use cadencelicensepatcher v2.0.0 to revert allegro 22, cadencelicensepatcher also Crashed！

**Comment by TerraWilly** [comment]
Hello bro,

Do not use it when your program is running.

I will release new version in next week.

thanks.

**Comment by TerraWilly** [comment]
Please download v2.3.0 version
