### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by 1864mp** [BinaryHackerLab/CadenceLicensePatcher#8]
Will this work for linux based Virtuoso IC6.1.8? Thanks.

**Comment by TerraWilly** [comment]
[FlexNetLicensePatcherLinux.zip](https://github.com/BinaryHackerLab/CadenceLicensePatcher/files/12908367/FlexNetLicensePatcherLinux.zip)

for linux: please use this

**Comment by 1864mp** [comment]
TerraWilly thanks for that.

**Comment by luoyanghero** [comment]
破解vmanager不彻底，复现步骤详见附件。

[vman-lic-debug.zip](https://github.com/user-attachments/files/18792994/vman-lic-debug.zip)

**Comment by KoustubhJain** [comment]
@TerraWilly does this also work with snps and mgc tools on linux?

Also, apologies but I tried using -p and -s commands while executing the FlexNetLicensePatcher from terminal and I gave path to required eda tool install directory as second argument and it still doesn't seem to work. Can anyone clarify how to properly use the tool ? @1864mp could you please clarify how to use the tool, if you have got it working ?

Edit: Please see #15
